color: null
fieldLayouts:
  ac3bd19b-91a8-4e27-b320-452d1625ef06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-20T01:07:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4021486b-4b07-4191-83f7-0436b9fc9873
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8dcfa048-c06b-49e7-b091-765aed0f341c
        userCondition: null
handle: contactUs
hasTitleField: true
icon: null
name: 'Contact Us'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
