altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  08ca2ee8-d531-45b4-9741-f329bc401a30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-20T18:22:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 495a5c0f-fe6b-45e5-86e0-d23715d71c73
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc3e0819-6ce0-4ab3-99cc-6ae8909bc480
        userCondition: null
fs: hardDisk
handle: images
name: Images
sortOrder: 2
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: images
