defaultPlacement: end
enableVersioning: true
entryTypes:
  - 531f6ffd-afc5-424d-80e2-6ccf35c1bfaf # Product
handle: products
maxAuthors: 1
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  545dbae7-338b-492a-a24b-9153a051d72a: # soa-ecommerce
    enabledByDefault: true
    hasUrls: true
    template: product
    uriFormat: 'products/{slug}'
type: channel
